### ISSUE TITLE
Is Stepzilla Responsive?

### ISSUE THREAD

**Issue by chobo2** [newbreedofgeek/react-stepzilla#102]
Hi

Is Stepzilla responsive for smaller screens?

**Comment by newbreedofgeek** [comment]
@chobo2 sorry for the delay.

StepZilla is "fairly" response out-of-the box, there is very little html markup as it just "wraps' your existing react "step" components:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js#L311-L339

So make sure your own step components are responsive and then wrap <StepZilla /> with your own responsive div.

Remember StepZilla does not have an css built in, you can style it anyway you want. We just provide sample css here as a starting point - https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/css/main.css

So yes, StepZilla is responsive because you can control the style and (most of the) markup.

Hope this helps and good luck with your project.
