### ISSUE TITLE
Problems running with NPM Start

### ISSUE THREAD

**Issue by Jvalal** [newbreedofgeek/react-stepzilla#128]
Hello - Having problems running this after I download the repo.

![image](https://user-images.githubusercontent.com/3803053/49473310-91699080-f7c6-11e8-9b76-96f88b218b1a.png)

**Comment by brennondenny** [comment]
If you want to run the examples locally run `npm install` then run `npm run example` then go to [http://localhost:8080/webpack-dev-server/src/examples/index.html](http://localhost:8080/webpack-dev-server/src/examples/index.html) in your browser.

`npm start` doesn't work because there is no start script.

**Comment by newbreedofgeek** [comment]
@brennondenny tnx for clarifying for @Jvalal 

Closing this.
