### ISSUE TITLE
Does not work with React.memo

### ISSUE THREAD

**Issue by hermanho** [newbreedofgeek/react-stepzilla#145]
Example: https://codesandbox.io/s/w2rzy3jnv5

The step 2 component is defined with React.memo and it will throw error "Cannot read property 'isValidated' of undefined" .

**Comment by newbreedofgeek** [comment]
Thanks for providing the demo URL - it probably has to do with how we deep search for isValidated https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/main.js#L242

memo is wrapping you component and this is breaking the linkage.

Did you work out a fix? if not I can look at it... but it will take me some time due to a overload in work.

**Comment by hermanho** [comment]
I replace with PureComponent class approach.

**Comment by zeel** [comment]
Opened pull request for this at [link](https://github.com/newbreedofgeek/react-stepzilla/pull/149)

**Comment by newbreedofgeek** [comment]
This should be fixed now (hopefully).. after PR #149 was closed
