### ISSUE TITLE
I get an error using the component

### ISSUE THREAD

**Issue by BesatZardosht** [newbreedofgeek/react-stepzilla#3]
I added the component:

`const StepZilla = require('react-stepzilla');
`

And my render method:
```
    render() {
        const stepOne = (
            <div >
                <h1> Hello </h1>
            </div>
        );
        const stepTwo = (
            <div >
                <h1> World </h1>
            </div>
        );
        const stepThree = (
            <div >
                <h1> !!! </h1>
            </div>
        );
        const steps =
            [
              { name: 'Step 1', component: <stepOne /> },
              { name: 'Step 2', component: <StepTwo /> },
              { name: 'Step 3', component: <stepThree /> },
            ];

        return (
            <div className="step-progress">
                <StepZilla steps={steps} />
            </div>
        );
    }
```

I get this error:
`React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)`

**Comment by newbreedofgeek** [comment]
I'm not sure you can create components like this in React (i.e. create components inside a render method of another component ) - which is why you are getting that error. When <stepOne /> is rendered React looks for its render method which should have a <div> as the root.

Have a look at the example for how you should be using StepZilla:
https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Example.js

**Comment by newbreedofgeek** [comment]
Closing this off as a question as I didn't hear back and it was not an issue.
