### ISSUE TITLE
Support Stateless Pure Components

### ISSUE THREAD

**Issue by muhilham** [newbreedofgeek/react-stepzilla#9]
I got this error while implement it on stateless component

`Warning: Stateless function components cannot be given refs (See ref "activeComponent" in ProductForm created by StepZilla). Attempts to access this ref will fail.`

**Comment by newbreedofgeek** [comment]
Hi @muhilham unfortunately you cannot use stateless pure components due to the fact that StepZilla clones the step components to append a ref so we can provide the jumpToStep() utility method. ref only works when you inherit from React Component (this is why pure components are not supported at the moment). 

In future we can enable a config param to disable this behaviour. i.e. disableJumpToStep = true/false

I'll put this as a enhancement and work on it when I have time. Or feel free to fork and send a pull request if you want to give it a go.

**Comment by wassimz** [comment]
@newbreedofgeek 
Can we use a wrapped component. I am using the react-validation-mixin to validate the form input an as a setup we need to wrap the component around the selected strategy. It seems that the isValidated() method not applied ??

**Comment by newbreedofgeek** [comment]
@wassimz it should be possible or I can have a look. Can you give me an example code on your StepZilla initialisation (with your wrapper), so I can reproduce the issue and fix.

**Comment by newbreedofgeek** [comment]
@wassimz I have created a new issue for your requirement #15

**Comment by wassimz** [comment]
Hi @newbreedofgeek 
I have tried to create an example (you can see it on my fork project (https://github.com/wassimz/react-stepzilla/blob/master/src/examples/Step22.js) but still not able to make it run (I am novice on react programming). So you can have a look on it and see how can I make it run.

Thanks

**Comment by newbreedofgeek** [comment]
@muhilham I've added support for Pure Components in react-stepzilla@4.2.0. Check out this file for how - https://github.com/newbreedofgeek/react-stepzilla/blob/master/src/examples/Step2.js
